apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ydata.ai
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ydata.ai
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- resources:
  - pods
  verbs:
  - create
- resources:
  - pods/status
  verbs:
  - get
